# Generated by Django 5.2.17 on 2026-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[("banner", "بنر"), ("ad", "تبلیغ")],
                        default="banner",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home_top", "بالای صفحه اصلی"),
                            ("home_middle", "میانه صفحه اصلی"),
                            ("sidebar", "سایدبار"),
                            ("article_bottom", "انتهای مقاله"),
                        ],
                        max_length=20,
                        verbose_name="جایگاه",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="banners/", verbose_name="تصویر"
                    ),
                ),
                (
                    "text",
                    models.CharField(blank=True, max_length=250, verbose_name="متن"),
                ),
                ("link", models.URLField(blank=True, verbose_name="لینک")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "بنر / تبلیغ",
                "verbose_name_plural": "بنرها و تبلیغات",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات SEO"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("body", models.TextField(verbose_name="متن (Markdown)")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "صفحه",
                "verbose_name_plural": "صفحات سایت",
                "ordering": ["order", "title"],
            },
        ),
    ]
