# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        help_text="خالی = مقدار پیش\u200cفرض از تنظیمات سرور",
                        max_length=100,
                        verbose_name="نام سایت",
                    ),
                ),
                (
                    "site_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیحات سایت (SEO)"
                    ),
                ),
                (
                    "default_og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="site/",
                        verbose_name="تصویر پیش\u200cفرض اشتراک\u200cگذاری (OG)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل تماس"
                    ),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="تلگرام")),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="ایکس (توییتر)"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="لینکدین")),
                (
                    "github_url",
                    models.URLField(blank=True, verbose_name="گیت\u200cهاب"),
                ),
                (
                    "head_scripts",
                    models.TextField(
                        blank=True,
                        help_text="فقط کد مورد اعتماد وارد کنید؛ بدون تغییر در head همه صفحات قرار می\u200cگیرد.",
                        verbose_name="کدهای head (آنالیتیکس)",
                    ),
                ),
                (
                    "comments_require_approval",
                    models.BooleanField(
                        default=False,
                        verbose_name="دیدگاه\u200cها قبل از نمایش تأیید شوند",
                    ),
                ),
                (
                    "banned_words",
                    models.TextField(
                        blank=True,
                        help_text="هر کلمه در یک خط",
                        verbose_name="کلمات ممنوع در دیدگاه\u200cها",
                    ),
                ),
                (
                    "ai_daily_auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="اگر خاموش باشد، AI Daily تولیدشده به\u200cصورت «در انتظار بررسی» ذخیره می\u200cشود.",
                        verbose_name="انتشار خودکار AI Daily",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
