# Generated by Django 5.2.17 on 2026-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="اینستاگرام"),
        ),
    ]
