# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین ویرایش"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="held_reason",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="دلیل نگه\u200cداشتن برای بررسی",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="حذف\u200cشده توسط کاربر"
            ),
        ),
    ]
