# Generated by Django 5.2.17 on 2026-09-28 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ai_daily", "AI Daily"), ("weekly", "خلاصه هفتگی")],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="شماره AI Daily یا هفته (مثلاً 2026-W39)",
                        max_length=50,
                        verbose_name="شناسه",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                (
                    "recipients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد گیرندگان"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "خبرنامه ارسال\u200cشده",
                "verbose_name_plural": "خبرنامه\u200cهای ارسال\u200cشده",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "key"), name="unique_issue")
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_article", "مطلب جدید"),
                            ("reply", "پاسخ به دیدگاه"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("url", models.CharField(max_length=500)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "wants_ai_daily",
                    models.BooleanField(default=True, verbose_name="AI Daily روزانه"),
                ),
                (
                    "wants_weekly",
                    models.BooleanField(default=True, verbose_name="خلاصه هفتگی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مشترک خبرنامه",
                "verbose_name_plural": "مشترکین خبرنامه",
                "ordering": ["-created_at"],
            },
        ),
    ]
