# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                verbose_name="ایمیل برای مطالب جدید موضوعات دنبال\u200cشده",
            ),
        ),
    ]
