# Generated by Django 5.2.17 on 2026-09-28 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات SEO"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="آیکون (ایموجی)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="نام"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات SEO"
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=240,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "مقاله"),
                            ("news", "خبر"),
                            ("tutorial", "آموزش"),
                            ("review", "بررسی تکنولوژی"),
                            ("ai_tool", "معرفی ابزار AI"),
                            ("open_source", "پروژه Open Source"),
                            ("research", "مقاله علمی"),
                            ("interview", "مصاحبه"),
                            ("video", "ویدئو"),
                            ("podcast", "پادکست"),
                            ("ai_daily", "AI Daily"),
                        ],
                        default="article",
                        max_length=20,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="covers/%Y/%m/", verbose_name="تصویر اصلی"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, max_length=500, verbose_name="خلاصه"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="از Markdown و بلوک\u200cهای ```code``` پشتیبانی می\u200cشود.",
                        verbose_name="متن (Markdown)",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="لینک ویدئو")),
                (
                    "audio_url",
                    models.URLField(blank=True, verbose_name="لینک فایل صوتی (پادکست)"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="منبع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="مهم\u200cترین مطلب روز"
                    ),
                ),
                (
                    "is_editor_pick",
                    models.BooleanField(default=False, verbose_name="منتخب سردبیر"),
                ),
                (
                    "reading_time",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, verbose_name="زمان مطالعه (دقیقه)"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="بازدید"
                    ),
                ),
                (
                    "ai_daily_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="شماره AI Daily",
                    ),
                ),
                (
                    "why_important",
                    models.TextField(blank=True, verbose_name="چرا مهم است؟"),
                ),
                (
                    "use_cases",
                    models.TextField(blank=True, verbose_name="چه کاربردی دارد؟"),
                ),
                (
                    "developer_impact",
                    models.TextField(
                        blank=True,
                        verbose_name="چه تأثیری روی توسعه\u200cدهندگان دارد؟",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="magazine.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="magazine.tag",
                        verbose_name="تگ\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مطلب",
                "verbose_name_plural": "مطالب",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="magazine_ar_status_3350e8_idx",
                    )
                ],
            },
        ),
    ]
