# Generated by Django 5.2.17 on 2026-09-28 05:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("feed_url", models.URLField(unique=True, verbose_name="آدرس RSS")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "منبع خبری AI",
                "verbose_name_plural": "منابع خبری AI Daily",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "permissions": [
                    ("publish_article", "می\u200cتواند مطلب منتشر یا ویژه کند (سردبیر)")
                ],
                "verbose_name": "مطلب",
                "verbose_name_plural": "مطالب",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="ai_generated",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="تولیدشده با AI"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="audio_file",
            field=models.FileField(
                blank=True,
                upload_to="podcasts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "ogg", "wav"]
                    )
                ],
                verbose_name="فایل صوتی (پادکست)",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="cover_variants",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                verbose_name="نسخه\u200cهای کوچک کاور",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="interviewee_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="نام مصاحبه\u200cشونده"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="interviewee_photo",
            field=models.ImageField(
                blank=True,
                upload_to="interviews/",
                verbose_name="عکس مصاحبه\u200cشونده",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="interviewee_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="سمت مصاحبه\u200cشونده"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="media_duration",
            field=models.CharField(
                blank=True,
                help_text="مثلاً 42:10",
                max_length=20,
                verbose_name="مدت ویدئو/پادکست",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="اطلاع\u200cرسانی به دنبال\u200cکنندگان",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="article",
            name="video_file",
            field=models.FileField(
                blank=True,
                upload_to="videos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "webm", "mov"]
                    )
                ],
                verbose_name="فایل ویدئو",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("review", "در انتظار بررسی"),
                    ("published", "منتشر شده"),
                ],
                default="draft",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="یوتیوب، آپارات یا لینک مستقیم",
                verbose_name="لینک ویدئو",
            ),
        ),
        migrations.CreateModel(
            name="InterviewQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="پرسش")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_qas",
                        to="magazine.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسش و پاسخ",
                "verbose_name_plural": "پرسش و پاسخ\u200cهای مصاحبه",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="uploads/%Y/%m/", verbose_name="تصویر"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین (alt)"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرنویس"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_files",
                        to="magazine.article",
                        verbose_name="مطلب",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر",
                "verbose_name_plural": "کتابخانه تصاویر",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleDailyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="magazine.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید روزانه",
                "verbose_name_plural": "بازدیدهای روزانه",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "date"), name="unique_daily_view"
                    )
                ],
            },
        ),
    ]
